#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libstemmer_c
Version  : 2.1.0
Release  : 7
URL      : https://snowballstem.org/dist/libstemmer_c-2.1.0.tar.gz
Source0  : https://snowballstem.org/dist/libstemmer_c-2.1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause
Requires: libstemmer_c-lib = %{version}-%{release}
Requires: libstemmer_c-license = %{version}-%{release}
Patch1: 0001-Make-libstemmer.so.patch

%description
libstemmer_c
============
This document pertains to the C version of the libstemmer distribution,
available for download from:

%package dev
Summary: dev components for the libstemmer_c package.
Group: Development
Requires: libstemmer_c-lib = %{version}-%{release}
Provides: libstemmer_c-devel = %{version}-%{release}
Requires: libstemmer_c = %{version}-%{release}

%description dev
dev components for the libstemmer_c package.


%package lib
Summary: lib components for the libstemmer_c package.
Group: Libraries
Requires: libstemmer_c-license = %{version}-%{release}

%description lib
lib components for the libstemmer_c package.


%package license
Summary: license components for the libstemmer_c package.
Group: Default

%description license
license components for the libstemmer_c package.


%prep
%setup -q -n libstemmer_c-2.1.0
cd %{_builddir}/libstemmer_c-2.1.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1619213337
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}  CFLAGS="-fPIC -Iinclude"


%install
export SOURCE_DATE_EPOCH=1619213337
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libstemmer_c
cp %{_builddir}/libstemmer_c-2.1.0/COPYING %{buildroot}/usr/share/package-licenses/libstemmer_c/f8d2c0ec1880e550ce455b2c660493b9d81f496d
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libstemmer.h
/usr/lib64/libstemmer.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libstemmer.so.0
/usr/lib64/libstemmer.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libstemmer_c/f8d2c0ec1880e550ce455b2c660493b9d81f496d
